// Bilingual Content Handler for 7Planner Website
// This script provides English translations for all pages

const bilingualContent = {
    'index.html': {
        zh: {
            title: '全能助理 隐私政策',
            navBrand: '全能助理',
            navHome: '首页',
            navSupport: '支持中心',
            navPrivacy: '隐私政策',
            effectiveDate: '生效日期：',
            lastUpdated: '最后更新：',
            appVersion: '应用版本：',
            supportedLanguages: '支持语言：',
            importantNotice: '重要提示：',
            offlineNotice: '是一款完全离线的任务管理应用。我们不会收集、存储或传输您的任何个人数据到我们的服务器。本应用现已支持全球发布，包括中国和所有其他国家。🌍',
            section1: '1. 信息收集',
            section1_1: '1.1 我们收集的信息',
            section1_1_desc: '在您的设备本地存储以下信息：',
            section1_2: '1.2 我们不收集的信息',
            section1_2_desc: '我们不会收集：',
            section2: '2. 数据存储',
            section2_1: '2.1 本地存储',
            section2_1_desc: '所有数据都存储在您的设备本地：',
            section2_2: '2.2 数据安全',
            section2_2_desc: '我们采用以下措施保护您的数据：',
            section3: '3. 数据使用',
            section3_1: '3.1 使用目的',
            section3_1_desc: '我们使用收集的数据仅用于：',
            section3_2: '3.2 数据共享',
            section3_2_desc: '我们不会与第三方共享您的数据：',
            section4: '4. 第三方服务',
            section4_1: '4.1 Apple 服务',
            section4_1_desc: '使用以下 Apple 服务：',
            section4_2: '4.2 权限使用',
            section4_2_desc: '应用可能请求以下权限：',
            section5: '5. 数据控制',
            section5_1: '5.1 您的权利',
            section5_1_desc: '您拥有以下权利：',
            section5_2: '5.2 数据删除',
            section5_2_desc: '您可以通过以下方式删除数据：',
            section6: '6. 儿童隐私',
            section7: '7. 隐私政策变更',
            section8: '8. 下载应用',
            section9: '9. 联系我们',
            section10: '10. 法律声明',
            footerUpdated: '本隐私政策最后更新于',
            footerBack: '返回首页',
            footerSupport: '支持中心'
        },
        en: {
            title: '7Planner Privacy Policy',
            navBrand: '7Planner',
            navHome: 'Home',
            navSupport: 'Support',
            navPrivacy: 'Privacy Policy',
            effectiveDate: 'Effective Date:',
            lastUpdated: 'Last Updated:',
            appVersion: 'App Version:',
            supportedLanguages: 'Supported Languages:',
            importantNotice: 'Important Notice:',
            offlineNotice: 'is a completely offline task management application. We do not collect, store, or transmit any of your personal data to our servers. This app now supports global release, including China and all other countries. 🌍',
            section1: '1. Information Collection',
            section1_1: '1.1 Information We Collect',
            section1_1_desc: 'stores the following information locally on your device:',
            section1_2: '1.2 Information We Do NOT Collect',
            section1_2_desc: 'We do not collect:',
            section2: '2. Data Storage',
            section2_1: '2.1 Local Storage',
            section2_1_desc: 'All data is stored locally on your device:',
            section2_2: '2.2 Data Security',
            section2_2_desc: 'We use the following measures to protect your data:',
            section3: '3. Data Usage',
            section3_1: '3.1 Purpose of Use',
            section3_1_desc: 'We use collected data only for:',
            section3_2: '3.2 Data Sharing',
            section3_2_desc: 'We do not share your data with third parties:',
            section4: '4. Third-Party Services',
            section4_1: '4.1 Apple Services',
            section4_1_desc: 'uses the following Apple services:',
            section4_2: '4.2 Permission Usage',
            section4_2_desc: 'The app may request the following permissions:',
            section5: '5. Data Control',
            section5_1: '5.1 Your Rights',
            section5_1_desc: 'You have the following rights:',
            section5_2: '5.2 Data Deletion',
            section5_2_desc: 'You can delete data in the following ways:',
            section6: '6. Children\'s Privacy',
            section7: '7. Privacy Policy Changes',
            section8: '8. Download App',
            section9: '9. Contact Us',
            section10: '10. Legal Statement',
            footerUpdated: 'This privacy policy was last updated on',
            footerBack: 'Back to Home',
            footerSupport: 'Support Center'
        }
    }
};

// Make it available globally
if (typeof window !== 'undefined') {
    window.bilingualContent = bilingualContent;
}

